dev: true
debug: true
database:
  url: mongodb://root:example@localhost:27017/admin?replicaSet=&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
  name: dating
server:
  port: 8000
  timeout: 30
cloudinary:
  url: cloudinary://243736193233756:GWLJJHLDN5oaMsUAX5lnmfxTrgE@paymax
  folder : /Users/Profile Photos
matching:
  new_users_time:
    year: 0
    month: -1
    day: 0
  nearby_distance: 7000 